name: Yad2 Scraper

on:
  schedule:
    - cron: '*/15 2-20 * * *'  # Every 15 min, 5AM-10PM Israel time (UTC+2/+3)
  workflow_dispatch:
    branches:
      - '**'

jobs:
  scraper:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install packages
        run: yarn install

      - name: Install Playwright browsers
        run: yarn playwright install chromium

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "${{ secrets.GIT_CONFIG_EMAIL }}"

      - name: Run scraper
        run: |
          export API_TOKEN=${{ secrets.API_TOKEN }}
          export CHAT_ID=${{ secrets.CHAT_ID }}
          yarn scrape

      - name: Push new json data if needed
        run: |
          if [ -f ./push_me ]; then
            echo "Checking for changes..."
            git add .
            if git diff --staged --quiet; then
              echo "No changes to commit, skipping push."
            else
              echo "Pushing to Github..."
              DATE=$(date +"%F, %H:%M:%S")
              git commit -m "updated data - $DATE"
              git push
            fi
          fi
